export const INCIDENT_TYPES = [
  "No Power",
  "Partial Power",
  "Other",
] as const;

export type IncidentType = (typeof INCIDENT_TYPES)[number];

export const INCIDENT_COLORS: Record<
  IncidentType,
  { text: string; bg: string; border: string; dot: string }
> = {
  "No Power": {
    text: "text-red-700",
    bg: "bg-red-50",
    border: "border-red-500",
    dot: "bg-red-500",
  },
  "Partial Power": {
    text: "text-amber-700",
    bg: "bg-amber-50",
    border: "border-amber-500",
    dot: "bg-amber-500",
  },
  Other: {
    text: "text-sky-700",
    bg: "bg-sky-50",
    border: "border-sky-500",
    dot: "bg-sky-500",
  },
};

export const SPECIAL_CONDITIONS = [
  "Wire Down",
  "Tree on Wire",
  "Pole Broken",
  "Wires Arcing",
  "Pole Fire",
];

export const STATUSES = [
  "UNASSIGNED",
  "CREW ASSIGNED",
  "SCOUTING",
  "SCOUTED",
  "TREE TRIMMERS ASSIGNED",
  "TREE TRIMMERS NEEDED",
  "COMPLETE",
];

export const CALL_TAKERS = [
  "Adelsberger",
  "Bachtell",
  "JD CLINE",
  "Cline(Mike)",
  "Fridinger",
  "Hess",
  "Hose",
  "Lloyd",
  "Overholser",
  "Schetrompf",
  "Stratton",
];

export const CREWS = [
  "UNASSIGNED",
  "TAPLEY",
  "TALBERT",
  "KRINER",
  "LUCAS",
  "DEVORE",
  "FRANK",
  "LORD",
  "ROHRER",
  "CAMPBELL",
  "LOVE",
  "CONTRACTOR",
];

export const FEEDERS = [
  "Bulldog 1", "Bulldog 2",
  "Fairgrounds 1", "Fairgrounds 2", "Fairgrounds 3", "Fairgrounds 4",
  "Frederick St 1", "Frederick St 2", "Frederick St 3", "Frederick St 4",
  "Mitchell 1", "Mitchell 2", "Mitchell 3", "Mitchell 4",
  "Plant 1", "Plant 2", "Plant 3", "Plant 4",
  "Wesel 1", "Wesel 2", "Wesel 3", "Wesel 4",
  "Zayre 1", "Zayre 2", "Zayre 3", "Zayre 4",
];

export const STREETS = [
  "ABBEY LN", "ACADEMIC BLVD", "ADAMS AVE", "ALEXANDER ST", "ALL STAR CT", "ANTIETAM DR", "ARLINGTON AVE", "ARMSTRONG AVE", "ATLANTA CT", "ATLANTIC AVE", "AUGUSTA CT", "AVALON AVE", "AVON RD", "AYOUB LN", "BARTOW DR", "BEACHLEY DR", "BEAVER CREEK RD", "BEECHWOOD DR", "BELVIEW AVE", "BENJAMIN PL", "BENTLEY CT", "BERNER AVE", "BESTER ST", "BEVERLY DR", "BIRCH RD", "BITTERSWEET DR", "BLAINE DR", "BLUE SPRUCE CIR", "BOWMAN AVE", "BOXWOOD CIR", "BRAMLY CT", "BRAMLY DR", "BRECCIA  WAY", "BREWER AVE", "BRIGHTON PL", "BRIGHTWOOD CIR", "BRIGHTWOOD DR", "BRILL WAY", "BRINKER DR", "BROADFORDING RD", "BROADWAY", "BROOKLINE AVE", "BROOKSIDE TERR", "BROWN AVE", "BRYAN PL", "BRYNWOOD STREET", "BUCKEY AVENUE", "BUELL CT", "BUENA VISTA AVE", "BUSINESS CENTER DR", "CALVERT TERR", "CAMEO DR", "CAMEO DRIVE", "CAPSTONE DR", "CARR ST", "CARROLL HEIGHTS BLVD", "CARROLTON AVE", "CATAWBA CIR", "CATAWBA PL", "CATHEDRAL AVE", "CAVALIER CT", "CEDAR CREST AVENUE", "CEDARLAWN DRIVE", "CEDARWOOD DR", "CENTER ST", "CENTRAL AVE", "CENTRE DRIVE", "CHAMBLISS DR", "CHANTILLY CT", "CHARLES ST", "CHARTRIDGE DR", "CHASE ST", "CHERRY HILL CIR", "CHERRY HILL DR", "CHESSIE LN", "CHESTNUT ST", "CHIMNEYSTONE CT", "CITY PARK  DRIVEWAY", "CITY PARK DRWAY", "CLAIRE ST", "CLARENDON AVE", "CLARKSON AVE", "CLEAN WATER CIR", "COBB CT", "COLUMBIA AE", "COLUMBIA AVE", "COLUMBIA RD", "COMMONWEALTH AVE", "CONAMAR DR", "CONCORD ST", "CONNECTICUT AVE", "CONRAD CT", "COOK ST", "CORBETT ST", "CORNELL AVE", "CORNELL AVENUE", "CORTLAND DRIVE", "COTTAGE CT", "COTTONWOOD DR", "COUNTRY CLUB RD", "COURTLAND DR", "CRESCENT RD", "CREST VIEW AVE", "CREST VIEW RD", "CRESTWOOD DR", "CRISTINS CIR", "CROFTON RD", "CROSS ST", "CYPRESS ST", "DALE ST", "DARTMOUTH DR", "DAY RD", "DAYCOTAH AVE", "DAYSPRING LANE", "DELAWARE LN", "DELWOOD AVENUE", "DEMON DEACON", "DEVONSHIRE RD", "DEWEY AVE", "DIAMOND DR", "DIVISION AVE", "DOUB WAY", "DOWNSVILLE RD", "DUAL HWY", "DUAL PL", "DUNN IRVIN DR", "DYNASTY DRIVE", "E ANTIETAM ST", "E BALTIMORE ST", "E BASALT WAY", "E FIRST ST", "E FRANKLIN ST", "E FRANKLIN STREET", "E HILLCREST RD", "E HOWARD ST", "E IRVIN AVE", "E LEE ST", "E MAGNOLIA AVE", "E MEMORIAL BLVD", "E NORTH AVE", "E OAK RIDGE DR", "E WASHINGTON ST", "E WILSON BLVD", "EAST AVE", "EAST PL", "EASTERN BLVD", "EASTERN BLVD S", "EASTERN BOULEVARD NORTH", "EASTRIDGE DR", "EASTVIEW DR", "EASTWOOD CT", "EASTWOOD DR", "EDGEWOOD AVE", "EDGEWOOD DR", "EDGEWOOD HILL CIR", "EDGEWOOD PL", "ELDRIDGE DR", "ELGIN BLVD", "ELIZABETH CT", "ELIZABETH ST", "ELM ST", "ELMWOOD RD", "EMMERT RD", "ENGLEWOOD RD", "EUTAW ST", "FAIR MEADOWS BLVD", "FAIRCHILD AVE", "FAIRGROUND AVE", "FAIRVIEW RD", "FALLEN TIMBERS CIR", "FARRAGUT WAY", "FLORIDA AVE", "FOREST DR", "FOREST ST", "FOUNTAIN HEAD RD", "FOUNTAINDALE WAY", "FOURTH ST", "FREDERICK ST", "FREEMONT ST", "FRIDINGER AVE", "FRY AVE", "FUNKSTOWN ROAD", "GANDY DANCER CT", "GARDENWOOD DRIVE", "GARLAND GROH BLVD", "GARLINGER AVE", "GARRETT ST", "GARST CT", "GEMSTONE DR", "GEORGE ST", "GEORGIA AVE", "GETTYSBURG WAY", "GLENWOOD AVE", "GREEN LN", "GREENWOOD CIR", "GREENWOOD DR", "GUILFORD AVE", "HAGER ST", "HAGERS CROSSING DR", "HALFWAY BLVD", "HAMILTON BLVD", "HAMILTON LN", "HAMMOND ST", "HAMPTON CIR", "HARVARD RD", "HARWOOD RD", "HAVEN RD", "HAWKINS CIR", "HAYES AVE", "HAYES CT", "HAYWOOD CIR.", "HEBB RD", "HEISKELL CT", "HEISTER ST", "HENRY AVE", "HIGH ST", "HIGHLAND AVE", "HIGHLAND WAY", "HILLSIDE DR", "HOLLEYMEAD TER", "HOLLYHOCK RD", "HONEYSUCKLE LN", "HOOD ST", "HOOSIER CT", "HOSPITAL WAY", "HOWELL RD", "HUMP RD", "HURRICANE", "IMPERIAL DRIVE", "INDIANA AVE", "INSURANCE WAY", "INTERSTATE 81", "INTERVAL RD", "IRIS CT", "IRVIN AVE", "J. V. JAMISON DR", "JACKSON AVE", "JADE COURT", "JAMES ST", "JAMISON CIRCLE", "JAY DR", "JEFFERSON ST", "JOHN F. KENNEDY DR.", "JOHN ST", "JUBAL CT", "KASINOF AVE", "KENLY AVE", "KENSINGTON DR", "KENWOOD DR", "KEY AVE", "KEY CIR", "KEY ST", "KEY WEST DR", "KILPATRICK CT", "KING ST", "KINGS CREST BLVD", "KINGSWOOD TER", "KINSLOW ST", "KLICK WAY", "KNIGHTSBRIDGE DR", "KUHN AVE", "LANDIS RD", "LANGDON ST", "LANGLEY DR", "LANVALE ST", "LARGO DR", "LAURAN RD", "LAUREL ST", "LAVA CT", "LAWTON LN", "LEHIGH AVE", "LEITERSBURG PIKE", "LEROY ST", "LIBERTY ST", "LILY CT", "LINDEN AVE", "LINDSAY LN", "LINGANORE AVE", "LINWOOD RD", "LITTLE ELLIOTT DR", "LITTLE HADEN CIR", "LONDONTOWNE CIR", "LONDONTOWNE DR", "LUTHER DR", "LYNN HAVEN DR", "MADISON AVE", "MAGMA CT", "MAGNOLIA CT", "MAHOGANY CIR", "MAHOGANY DR", "MAIN AVE", "MANILA AVE", "MANOR DR", "MAPLE AVE", "MAPLEWOOD DR", "MARATHON DR", "MARION ST", "MARSHALL ST", "MARYLAND AVE", "MASSEY BLVD", "MATRIC CT", "MATTHEW CT", "MAUGANSVILLE RD", "MAY ST", "MCCAULEY CT", "MCCOMAS ST", "MCDADE RD", "MCDOWELL AVE", "MCKEE AVE", "MCPHEARSON ST", "MCRAND CT", "MCSWAIN CT", "MD RTE 58", "MEADOW AVE", "MEADOW VIEW DR", "MEALEY PKWY", "MECHANIC ST", "MEDICAL CAMPUS RD", "MEDWAY RD", "MERCER DR", "MERIDIAN DR", "MERRBAUGH DR", "MICHIGAN AVE", "MILES ST", "MILL ST", "MILLS PARK DWY", "MINERAL AVE", "MITCHELL AVE", "MOLLER AVE", "MOLLER PKWY", "MONET DR", "MONROE AVE", "MONTCLAIR CT", "MORNINGSIDE AVE", "MOUNT AETNA", "MT AETNA RD", "MULBERRY AVE", "MURDOCK AVE", "MURPH AVE", "MUSEY AVE", "N BURHANS BLVD", "N CANNON AVE", "N CLEVELAND AVE", "N COLONIAL DR", "N JONATHAN ST", "N LOCUST ST", "N MONT VALLA", "N MULBERRY ST", "N POTOMAC ST", "N PROSPECT ST", "N WALNUT ST", "NAPLES DR", "NATIONAL PIKE", "NITTANY LION CIR", "NOLAND DR", "NORTHERN AVE", "NORWAY AVE", "NOTTINGHAM RD", "OAK HILL AVE", "OAK RIDGE DR", "OAK ST", "OBSERVATORY DR", "OLD FORGE RD", "OLIVINE CT", "OMEGA DRIVE", "OPAL CT", "ORCHARD TERRACE RD", "OSBORNE AVE", "OUTER CIR", "OUTER CT", "OUTER DR", "OVERBROOK DR", "OXFORD CIR", "PALM BEACH DR", "PALMWOOD CIR", "PANGBORN BLVD", "PAPA CT", "PARK AVE", "PARK LN", "PARK PL", "PARK RD", "PARKWAY DR", "PARKWOOD CT", "PARKWOOD DR", "PATTERSON DR", "PAUL SMITH BLVD", "PELETON ST", "PENNSYLVANIA AVE", "PERLITE WAY", "PICADILLY DR", "PINE ST", "PINECREST AVE", "PINEWOOD CIR", "PLATEAU CT", "PLUMWOOD CIR", "PLUMWOOD DR", "POINT SALEM RD", "POPE AVE", "POTOMAC AVE", "POTOMAC HEIGHTS", "S CANNON AVE", "S CLEVELAND AVE", "W BETHEL ST", "W CHURCH ST", "W FIRST ST", "W MAGNOLIA AVE", "W MEMORIAL BLVD", "PUBLIC SQ", "PULLMAN LANE", "QUEEN ANNES CT", "RADCLIFF AVE", "RAILWAY LN", "RAMP", "RAMP 81", "RANDOLPH AVE", "RAVENSWOOD DR", "RAY ST", "REDWOOD CIR", "REDWOOD DR", "REYNOLDS AVE", "RHODE ISLAND AVE", "RICHMOND ST", "RICHWOOD DRIVE", "RIDGE AVE", "ROBINS GLENN DR", "ROBINWOOD CT", "ROBINWOOD DR", "ROCK WILLOW AVE", "ROSE HILL AVE", "ROSEBANK WAY", "ROSENCRANS DR", "ROSS ST", "ROWLAND AVE", "S BURHANS BLVD", "S COLONIAL DR", "S DUAL PL", "S LOCUST ST", "S MONT VILLA AVE", "S MULBERRY ST", "S POTOMAC ST", "S PROSPECT ST", "S WALNUT ST", "ST CLAIR ST", "SALEM AVE", "SALEM AVENUE EXT", "SANI LN", "SECURITY RD", "SEDGWICK DR", "SHALE DR", "SHANK WAY", "SHERMAN AVE", "SHORT RD", "SINTER WAY", "SLATE WAY", "SNYDER AVE", "SOUTH ST", "SPRECHER AVE", "SPRUCE ST", "STALEY DR", "STANFORD RD", "STAR DR", "STONE HOUSE WAY", "STRATFORD AVE", "STURGIS", "SUMANS AVE", "SUMMER ST", "SUMMIT AVE", "SUNBROOK LN", "SUNNYSIDE DR", "SUNSET AVE", "SURREY AVE", "SWANN RD", "SWEENY DR", "SWEET BRIAR LN", "SYCAMORE ST", "TANDY DR", "TAYLOR AVE", "TEAKWOOD DR", "TERPS  BLVD", "THAMES ST", "THE TERRACE", "THIRD ST", "TOP FLITE CT", "TRACYS LN", "TRAFALGAR DR", "TUDOR", "TULIP CT", "TULSA LN", "UNDERPASS WAY", "UNION PL", "VALE ST", "VALLEY RD", "VALLEYBROOK DR", "VARSITY LANE", "VERMONT AVE", "VICKIE DR", "VIEW ST", "VILLAGE PL", "VIOLET DR", "VIRGINIA AVE", "VISTA ST", "W ANTIETAM ST", "W BALTIMORE ST", "W BASALT WAY", "W FRANKLIN ST", "W HILLCREST RD", "W HOWARD ST", "W IRVIN AVE", "W LEE ST", "W NORTH AVE", "W WASHINGTON ST", "W WILSON BLVD", "WABASH AVE", "WAKEFIELD RD", "WASHINGTON AVE", "WATER ST", "WAYNE AVE", "WAYSIDE AVE", "WELLINGTON AVE", "WESEL BLVD", "WESTERN MARYLAND PKWY", "WESTLAWN LANE", "WESTPORT DR", "WESTSIDE AVE", "WESTWOOD ST", "WHITTIER HTS", "WILLARD ST", "WILLOW CIR", "WILLOWBROOK WAY", "WINSTON DR", "WINTER ST", "WISE ST", "WOLFPACK WAY", "WOOD ST", "WOODBRIDGE AVE", "WOODBRIDGE DR", "WOODLAND WAY", "WOODLANDS RUN", "WOODLAWN DRIVE", "WOODPOINT AVE", "WYOMING AVE", "YALE DR", "YELLOW JACKET RD", "YORKSHIRE DR", "YOUNG AVE", "YOUNGSTOUN DR", "PROSPECT AVE",
];
