create table public.tg_briefings (
  id text primary key,
  created_at timestamptz not null default now(),

  task_description text,
  job_address text,
  date_time timestamptz,
  work_order text,
  hospital text,
  emergency text,
  person_in_charge text,
  crew_present text[],
  vehicles_present text[],
  hazards text[],
  work_procedures text,
  special_precautions text,
  substation text,
  feeder text,
  pole text,
  delivery_point text,
  recloser_disabled boolean,
  hot_line_tag boolean,
  ppe text[],
  work_gloves text[],
  reviewed_by text,
  reviewed_date_time timestamptz,
  additional_notes text
);

create table public.veh_inspections (
  id text primary key,
  created_at timestamptz not null default now(),

  date date,
  unit text,
  name text,
  mileage text,
  misc_notes text,
  operator_name text,
  operator_signature text,
  results jsonb
);

create table public.crew_reports (
  id text primary key,
  created_at timestamptz not null default now(),

  wo text,
  date date,
  name text,
  job_type text,
  job_location text,
  crew_members text,
  truck_types text,
  special_tools text,
  comments text,
  sections jsonb,
  deficiency_comments text
);

create table public.veh_accident_reports (
  id text primary key,
  created_at timestamptz not null default now(),

  accident_date date,
  accident_time text,
  driver_name text,
  employee_number text,
  location text,
  city_vehicle_no text,
  city_vehicle_year text,
  city_vehicle_model text,
  city_vehicle_make text,
  city_vehicle_other_desc text,
  other_vehicle_tag text,
  other_vehicle_year text,
  other_vehicle_model text,
  other_vehicle_make text,
  other_vehicle_other_desc text,
  other_driver_name text,
  other_driver_address text,
  other_driver_phone text,
  ins_co text,
  ins_agent text,
  ins_policy_no text,
  witness1 text,
  witness2 text,
  injury1 text,
  injury2 text,
  city_vehicle_damage text,
  other_vehicle_damage text,
  property_damage text,
  illumination text,
  weather text,
  accident_type text,
  road_surface text,
  road_condition text,
  speed_limit text,
  cause text[],
  driver_description text,
  driver_role_fault text,
  driver_role_preventable text,
  police_report_by text,
  citations_issued text,
  other_comments text,
  driver_signature text,
  preparer_signature text,
  driver_report_date date,
  supervisor_role_fault text,
  supervisor_role_preventable text,
  supervisor_comments text,
  supervisor_signature text,
  supervisor_date date,
  was_driver_interviewed text,
  manager_role_fault text,
  manager_role_preventable text,
  manager_assessment text,
  disciplinary_action text,
  manager_signature text,
  manager_date date,
  agree_facts text,
  agree_facts_explain text,
  agree_role text,
  agree_role_explain text,
  review_comments text,
  review_signature text,
  review_date date,
  committee_notes text,
  committee_review_date date,
  committee_chairman_signature text
);

create table public.employee_accident_reports (
  id text primary key,
  created_at timestamptz not null default now(),

  employee_name text,
  employee_number text,
  job_title text,
  department text,
  incident_date date,
  incident_time text,
  date_reported date,
  supervisor_name text,
  location text,
  description text,
  injury_types text[],
  body_parts text[],
  first_aid_given text,
  medical_treatment_sought text,
  treatment_facility text,
  lost_work_time text,
  return_to_work_date date,
  witness1 text,
  witness2 text,
  equipment_involved text,
  ppe_worn text[],
  contributing_factors text[],
  corrective_actions text,
  employee_signature text,
  employee_sign_date date,
  supervisor_signature text,
  supervisor_sign_date date,
  supervisor_preventable text,
  supervisor_assessment_comments text,
  committee_review_date date,
  committee_chairman_signature text,
  committee_notes text
);
